### ISSUE TITLE
How do you prefer to have proxy support?

### ISSUE THREAD

**Issue by miguelff** [tj/google-search#2]
Hi TJ,

I've checked out your gem because I need to create a toy metasearch engine, the thing is that I need to have proxy support to pass through my university network, and I was about to create a patch. 

As you already know, adding proxy support is trivial but, in order to keep the excellent usability of the API I was wondering which one of the following approaches would you prefer me to follow:
* On the one side, I can keep the stateless, self-containing style of the queries and do what's necessary to allow something like this:

```ruby
Google::Search::Web.new(:query => 'naked celebrities',  :proxy => 'http://proxy.uniovi.es:8888').each do |web_result|
   #... Whatever
 end
```

* On the other side, it could be interesting to have a means of configuring a proxy for all the queries, as it is very likely that someone needing a proxy to submit a query, would need it to submit all of them:

```ruby
Google::Search::Defaults.set(:proxy, 'http://proxy.uniovi.es:8888')
Google::Search::Web.new(:query => 'naked celebrities').each{ | web_result | ... }
Google::Search::Images.new(:query => 'angelina jolie').each{ | image | ... }
Google::Search::Local.new(:query => 'foo bar').each{ |place| ... }
```
Both alternatives can be complementary.

Do you think that having a Defaults object would break your API orthogonality? having it would ease the case of needing a proxy, which IMHO is not that uncommon, but I would like to know your opinion.

Regards,

Miguel

**Comment by sevk** [comment]
I need proxy too , thank you .
